[2020-06-02 14:48:23,107] {logging_mixin.py:112} INFO - Sending to executor.
[2020-06-02 14:48:23,108] {logging_mixin.py:112} INFO - [2020-06-02 14:48:23,108] {base_executor.py:58} INFO - Adding to queue: ['airflow', 'run', 'covid_dag', 'covid_data', '2020-05-30T00:00:00+00:00', '--force', '--local', '--pool', u'default_pool', '-sd', 'DAGS_FOLDER/covid_data.py']
[2020-06-02 14:48:23,108] {logging_mixin.py:112} INFO - [2020-06-02 14:48:23,108] {sequential_executor.py:45} INFO - Executing command: ['airflow', 'run', 'covid_dag', 'covid_data', '2020-05-30T00:00:00+00:00', '--force', '--local', '--pool', u'default_pool', '-sd', 'DAGS_FOLDER/covid_data.py']
[2020-06-02 14:48:24,768] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag.covid_data 2020-05-30T00:00:00+00:00 [success]>
[2020-06-02 14:48:24,774] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag.covid_data 2020-05-30T00:00:00+00:00 [success]>
[2020-06-02 14:48:24,774] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-06-02 14:48:24,774] {taskinstance.py:867} INFO - Starting attempt 2 of 3
[2020-06-02 14:48:24,774] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-06-02 14:48:24,792] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): covid_data> on 2020-05-30T00:00:00+00:00
[2020-06-02 14:48:24,795] {standard_task_runner.py:53} INFO - Started process 12960 to run task
[2020-06-02 14:48:24,848] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_dag.covid_data 2020-05-30T00:00:00+00:00 [running]> nineleaps
[2020-06-02 14:48:29,457] {logging_mixin.py:112} INFO - csv loaded successfully.
[2020-06-02 14:48:29,457] {python_operator.py:114} INFO - Done. Returned value was: None
[2020-06-02 14:48:29,460] {taskinstance.py:1048} INFO - Marking task as SUCCESS.dag_id=covid_dag, task_id=covid_data, execution_date=20200530T000000, start_date=20200602T091824, end_date=20200602T091829
[2020-06-02 14:48:34,765] {logging_mixin.py:112} INFO - [2020-06-02 14:48:34,765] {local_task_job.py:103} INFO - Task exited with return code 0
[2020-06-03 08:17:31,257] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag.covid_data 2020-05-30T00:00:00+00:00 [queued]>
[2020-06-03 08:17:31,265] {taskinstance.py:655} INFO - Dependencies all met for <TaskInstance: covid_dag.covid_data 2020-05-30T00:00:00+00:00 [queued]>
[2020-06-03 08:17:31,265] {taskinstance.py:866} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 08:17:31,265] {taskinstance.py:867} INFO - Starting attempt 2 of 3
[2020-06-03 08:17:31,265] {taskinstance.py:868} INFO - 
--------------------------------------------------------------------------------
[2020-06-03 08:17:31,282] {taskinstance.py:887} INFO - Executing <Task(PythonOperator): covid_data> on 2020-05-30T00:00:00+00:00
[2020-06-03 08:17:31,285] {standard_task_runner.py:53} INFO - Started process 30410 to run task
[2020-06-03 08:17:31,343] {logging_mixin.py:112} INFO - Running %s on host %s <TaskInstance: covid_dag.covid_data 2020-05-30T00:00:00+00:00 [running]> nineleaps
[2020-06-03 08:17:32,957] {taskinstance.py:1128} ERROR - string indices must be integers
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/airflow/models/taskinstance.py", line 966, in _run_raw_task
    result = task_copy.execute(context=context)
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 113, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python2.7/dist-packages/airflow/operators/python_operator.py", line 118, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/home/nineleaps/airflow/dags/covid_data.py", line 69, in get_covid_data
    csv_writer.writerow([context['execution_date'], i['State UT'], i[str(context['execution_date']).split('T')[0]]])
TypeError: string indices must be integers
[2020-06-03 08:17:32,959] {taskinstance.py:1151} INFO - Marking task as UP_FOR_RETRY
[2020-06-03 08:17:41,254] {logging_mixin.py:112} INFO - [2020-06-03 08:17:41,253] {local_task_job.py:103} INFO - Task exited with return code 1
